language: php
php:
  - 5.5.9
  - 5.6
  - 7
  - hhvm
matrix:
  allow_failures:
  - php: hhvm
sudo: false
before_script:
  - travis_retry composer install
  - travis_retry npm install
script:
  - ./vendor/bin/phpunit -c core/phpunit.xml 
